### ISSUE TITLE
Option to define the badge size within the README

### ISSUE THREAD

**Issue by samtrion** [pemtajo/badge-readme#9]
It would be great if you could add an option that defines the badge size in the README view.
Something similar to ...
| Option | Default Value | Description | Required |
|--------|---------------|-------------|--------|
|*BADGE_SIZE*| 110 |Defines the badge dimension.|No|

After a little fiddling with Credly's URL structure, I figured out that you can manipulate the URL. If I replace the string `/110x110/` with `/150x150/`, I get the following result.

Which makes a significant difference depending on the README profile design.

| Default Size 110x110 | Overriden Size 150x150 |
|:--------------------:|:----------------------:|
|![Microsoft Certified: Security, Compliance, and Identity Fundamentals](https://images.credly.com/size/110x110/images/fc1352af-87fa-4947-ba54-398a0e63322e/security-compliance-and-identity-fundamentals-600x600.png)|![Microsoft Certified: Security, Compliance, and Identity Fundamentals](https://images.credly.com/size/150x150/images/fc1352af-87fa-4947-ba54-398a0e63322e/security-compliance-and-identity-fundamentals-600x600.png)|

Further facts, which I could determine. The value should not exceed 600px width or height. Since most badges were deposited in this dimension size.

**Comment by samtrion** [comment]
any progress on this?

**Comment by pemtajo** [comment]
Done
